# Generated by Django 3.1.3 on 2021-06-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210524_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created']},
        ),
    ]
