# Generated by Django 3.1.3 on 2021-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0005_auto_20210509_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='catagory',
        ),
        migrations.AddField(
            model_name='images',
            name='catagory',
            field=models.ManyToManyField(blank=True, default=None, related_name='catagory', to='gallary.Catagory'),
        ),
    ]
