# Generated by Django 3.1.3 on 2021-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0006_auto_20210509_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
