# Generated by Django 3.1.3 on 2021-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0007_auto_20210509_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='images',
            name='subCat',
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
