# Generated by Django 3.1.3 on 2021-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0012_auto_20210519_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='catagory',
            new_name='category',
        ),
    ]
